// <auto-generated />
namespace E_Shop_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitiallyAddedUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitiallyAddedUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202001051430527_InitiallyAddedUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
